### ISSUE TITLE
get writable extension list

### ISSUE THREAD

**Issue by diverlin** [AcademySoftwareFoundation/OpenImageIO#1112]
is it possible to get extension list only for writable extensions(for example excluding .raw (avaliable only for read))?

we may get list of supported for reading extensions by using:
std::string &extensions;
getattribute ("extension_list", extensions);

Cheers, Alex

**Comment by lgritz** [comment]
Well, I guess you could ask for the "extension_list", and then try an ImageOutput::create() for each format, building a list of which ones succeed. (Don't forget to destroy them, though, so you don't leak a bunch of empty ImageOutput's.)

Would it be helpful to have a built-in query that gives you the writeable extensions, or is this method sufficient?

**Comment by lgritz** [comment]
Closing, as this was long ago fixed by #1577 which added a new getattribute query for "output_format_list"
