### ISSUE TITLE
Can not load PSD with feather mask

### ISSUE THREAD

**Issue by CenekStrichel** [AcademySoftwareFoundation/OpenImageIO#1209]
I reported bug in Blender, but I was redirected here. https://developer.blender.org/T46022

**Comment by lgritz** [comment]
I can reproduce this, but I'm not sure how to fix it. I can get the Mac Preview.app to show it, but GIMP is also unable to open the flie. So that indicates to me that either the file really is incorrect (and Mac preview is very tolerant of this particular error), or that the file is legal but somehow touches on an obscure or tricky part of the PSD that multiple independently-developed applications fail to read properly.

**Comment by olear** [comment]
ImageMagick is able to read the file, don't support the mask, but is at least able to read the image/layers...
```
tst.psd[0] PSD 2048x2048 2048x2048+0+0 8-bit sRGB 1.379MB 0.010u 0:00.009
tst.psd[1] PSD 2048x2048 2048x2048+0+0 8-bit sRGB 1.379MB 0.030u 0:00.020
```
![snapshot1](https://cloud.githubusercontent.com/assets/7461595/12585453/70fa5628-c44c-11e5-9077-902a2f560b42.png)

**Comment by lydia-zheng** [comment]
Hi All!

After some investigating with the source feather mask psd, it seems like there is a good chance that there was something wrong or at least very unusual about the file, given we have a subimage of size 0x0 amongst 3 subimages. The psd was further tested for behavior with several programs, with inconsistent results.

As such, unless there are further cases of reproducible failure that indicated an edge case in OIIO, this may be an one-off problem.

**Fails to open in:**
* Gimp
    `Opening 'tst.psd' failed: Error loading PSD file: Unexpected end of file`
* Blender
    `File format is not supported in file: tst.psd`
* Krita
    `Reason: The File Format cannot be parsed`

**Opens in:**
* ImageMagick
    Opens layer without the feather masking


A different instance of psd was created to gauge if this is a persisting trait of the feather mask feature. However, there were no subimage of 0x0 in the second test psd.

**Error and File Metadata:**
```
oiiotool ERROR: -o : openexr image resolution must be at least 1x1, you asked for 0x0
3 subimages: 2048x2048 [u8,u8,u8,u8], 2048x2048 [u8,u8,u8,u8], **0x0** [u8,u8,u8,u8]
```

**Comment by lgritz** [comment]
Thanks for investigating, Lydia. I agree that if multiple programs are all having trouble with this file, it's probably a corrupted file, or maybe a technically correct file that's doing something so unusual that other readers are having trouble, too. I think we can close this ticket. If further problems are encountered, we can always re-open or start a new issue.
