### ISSUE TITLE
Cube map comparison with idiff always fails

### ISSUE THREAD

**Issue by inequation** [AcademySoftwareFoundation/OpenImageIO#140]
Steps to reproduce:

1) check out and build my DDS branch (https://github.com/inequation/oiio/tree/dds),
2) iconvert any cube map (e.g. this one: http://www.speedyshare.com/files/29882163/Animus128.dds) from DDS back to DDS,
3) compare images with idiff - always FAIL.

Note that upon visual inspection the images are identical.

Also using a "proxy" format for comparison (e.g. converting both images to PNG and comparing those) results in a PASS.

Difference image is somewhat weird - the first cube face is totally black (i.e. no difference), but the others are there unchanged, as if we were comparing the original image with a black one.

It may be a bug of mine. The fact that the first face passes comparison suggests that it might have something to do with the fact that a DDS cube map's full_width/height is the size of the cube map, while the spec.width/height are dimensions of the entire map.

**Comment by lgritz** [comment]
I'm going to assume that if 13 years whizzed by without anybody else complaining, nor with anyone feeling the need to propose a PR to fix it, that this (while possibly a bug) isn't on anybody's radar as worth spending time on. Closing.
