### ISSUE TITLE
[BUG] Invalid write crash when opening certain RAW images

### ISSUE THREAD

**Issue by AdamMainsTL** [AcademySoftwareFoundation/OpenImageIO#3115]
**Describe the bug**
When opening some RAW images I get a hard crash in my application when opening them with `raw:Demosaic = "none"`. Specifically the debugger says:

```
HEAP[prog.exe]: Heap block at 000002166E310F50 modified at 000002166E312908 past requested size of 19a8
```

Crash stack for reference:
![image](https://user-images.githubusercontent.com/51178903/135333882-46af63d2-25cf-445d-bc63-60bbb122787d.png)

**To Reproduce**
1. Download image from evidence
2. Open image
3. Crash

**Expected behavior**
No crash please. Would expect it to throw an exception we can handle.

**Evidence**
Here is a direct link to the images which should be able to reproduce the crash. Just in case I'll also zip it and attach them here.

http://www.rawsamples.ch/raws/pentax/RAW_PENTAX_K5IIS.PEF
[RAW_PENTAX_K5IIS.zip](https://github.com/OpenImageIO/oiio/files/7254452/RAW_PENTAX_K5IIS.zip)

http://www.rawsamples.ch/raws/nikon/d1x/RAW_NIKON_D1X.NEF
[RAW_NIKON_D1X.zip](https://github.com/OpenImageIO/oiio/files/7254512/RAW_NIKON_D1X.zip)

http://www.rawsamples.ch/raws/canon/40d/RAW_CANON_40D_SRAW_V103.CR2
[RAW_CANON_40D_SRAW_V103.zip](https://github.com/OpenImageIO/oiio/files/7254529/RAW_CANON_40D_SRAW_V103.zip)

http://www.rawsamples.ch/raws/kodak/RAW_KODAK_C330_FORMAT422_YRGB.RAW
[RAW_KODAK_C330_FORMAT422_YRGB.zip](https://github.com/OpenImageIO/oiio/files/7254552/RAW_KODAK_C330_FORMAT422_YRGB.zip)

http://www.rawsamples.ch/raws/kodak/RAW_KODAK_C330_FORMAT420_YRGB.RAW
[RAW_KODAK_C330_FORMAT420_YRGB.zip](https://github.com/OpenImageIO/oiio/files/7254548/RAW_KODAK_C330_FORMAT420_YRGB.zip)

http://www.rawsamples.ch/raws/kodak/RAW_KODAK_C330_FORMAT_NONE_YRGB.RAW
[RAW_KODAK_C330_FORMAT_NONE_YRGB.zip](https://github.com/OpenImageIO/oiio/files/7254546/RAW_KODAK_C330_FORMAT_NONE_YRGB.zip)

**Platform information:**
 - OIIO branch/version: 2.3.7.2
 - OS: Windows
 - C++ compiler: VS 2019
 - Any non-default build flags when you build OIIO: libraw, heic support

**Comment by lgritz** [comment]
I see what's going on now.

**Comment by lgritz** [comment]
Fix proposed in #3125 

Do you have the ability to apply that patch on your end and verify that it works for all the cases that crashed for you?

**Comment by AdamMainsTL** [comment]
I got this built and loaded, but it still crashes on 4/6 of the images listed above. This patch does seem to fix the NEF and PEF files though.

For the other 4 (Canon CR2 and all the Kodak files), they crash in `convert_pixel_values`:

![image](https://user-images.githubusercontent.com/51178903/136984603-9d674bf1-25c4-4a89-945b-81f2d40e81b0.png)

I do have several other images that I may not be able to post to evidence that crash, but I'll try to check if any of them crash in a unique way outside of the above stack trace.

**Comment by AdamMainsTL** [comment]
I've certainly had that feeling before. Thank you very much for working on this!

**Comment by lgritz** [comment]
It looks like I fixed the non-rotated case, but the rotated cases are doing the wrong thing when not demosaicing.
I'm a little afraid of clobbering the in-progress of @shootfast who says he has in-progress patches about this very issue, so I'm considering just handing the problem off to him (which he may have already fixed, for all I know).

**Comment by fabiencastan** [comment]
What is the status of this issue?

**Comment by Shootfast** [comment]
Just bumping this for my own benefit. I'm sorry about the absolute snails pace of updates / development. I am hoping to have something very soon.
