### ISSUE TITLE
iv - crashes trying to open non-image file

### ISSUE THREAD

**Issue by sambler** [AcademySoftwareFoundation/OpenImageIO#321]
starting iv from a terminal with a command such as 

iv /home/shane/images/*

where images contains image files as well as another dir and a text file, then cycle through images with PgUp/PgDwn causes iv to crash when a non-image file is the next item in the list. Similarly if just the dir is sent without the trailing /\* then it crashes trying to open it.

**Comment by lgritz** [comment]
Closing, because I think this is fixed now! #4010 made it so that giving a directory name to iv opens all the image files in the directory.
