### ISSUE TITLE
[BUG] It seems that all the tests are not being built and not all tests pass

### ISSUE THREAD

**Issue by Pixel-Minions** [AcademySoftwareFoundation/OpenImageIO#3794]
**Describe the bug**
I have built openimageio, and it seems in my smoke tests with the basic dependencies it works fine.
But not all tests pass, only 26 of 126 are passing, basically, all the tests found in the testsuite are not working. Some of the folders in the build folder are empty.

**To Reproduce**
1. Build v 2.4.9.0
2. In the build folder run ctest -V
3. It passes 26 out of 126 tests (21%)

**Expected behavior**
Pass 100% of the tests.

**Evidence**
Attached the logs and one screen capture.

**Platform information:**
 - OIIO branch/version: Tag 2.4.9.0
 - OS: Windows
 - C++ compiler: vc142 (cmake + nmake)
 - Any non-default build flags when you build OIIO: no, 

```cmd
cmake -DVERBOSE=ON -DCMAKE_BUILD_TYPE=Release -G"NMake Makefiles" ^
    -DBoost_USE_STATIC_LIBS=ON -DBoost_NO_WARN_NEW_VERSIONS=ON -DBOOST_ROOT="D:/Repositories/boost_1_79_0/stage/x64" ^
    -DZLIB_ROOT="D:/Repositories/zlib-1.2.13/build" ^
    -DTIFF_ROOT="D:/Repositories/tiff-4.5.0/install" ^
    -DOpenEXR_ROOT="D:/Repositories/openexr-3.1.6/install" ^
    -DImath_DIR="D:/Repositories/Imath-3.1.7/install/lib/cmake/Imath" ^
    -DJPEG_ROOT="D:/Repositories/libjpeg-turbo-2.1.5.1/install" ^
    -DUSE_PYTHON=0 -DUSE_QT=0 -DBUILD_SHARED_LIBS=0 -DLINKSTATIC=1 . -B ./build
```

[LastTestsFailed.log](https://github.com/OpenImageIO/oiio/files/11070895/LastTestsFailed.log)
[LastTest.log](https://github.com/OpenImageIO/oiio/files/11070896/LastTest.log)
making a [pull request](https://github.com/OpenImageIO/oiio/pulls).
![image](https://user-images.githubusercontent.com/1145623/227758270-aeb908f7-7ff9-4630-a5df-b4ec388f4a1f.png)

**Comment by lgritz** [comment]
This seems to have slipped through the cracks. Apologies for not responding right away.

If you get these test failures, you should be able to `cd build/testsuite/<the_failed_test>` and see a file called `out.txt` (and sometimes also `out.err.txt`) that contain the console output of the test, including error messages. Does looking at these for any of the failed tests give any clues about what BAD_COMMAND it's having trouble with or why it failed?

**Comment by lgritz** [comment]
Closing for no response and probably not really being broken (it passes in our CI on Windows, so probably just a path problem).
