### ISSUE TITLE
feat(raw): Expose max_raw_memory_mb setting

### ISSUE THREAD

**Issue by JenusL** [AcademySoftwareFoundation/OpenImageIO#3881]
**Is your feature request related to a problem? Please describe.**
We have some huge DNG-files that we're unable to develop with the default memory allocation in libraw.

**Describe the solution you'd like**
I would like the `imgdata.rawparams.max_raw_memory_mb` in libraw to be exposed as a `raw:max_raw_memory_mb` setting.

**Describe alternatives you've considered**
We have recompiled libraw with a higher default memory allocation to get around the problem but that isn't optimal.

**Additional context**
We have tested it to make sure that this setting will actually solve our problem.

**Comment by lgritz** [comment]
🎣 Mackerel!

**Comment by ankmachine** [comment]
going to take this one up for "dev days"

**Comment by ankmachine** [comment]
I have created PR to address this feature https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4454 , but not able to add any reviewer for some reason.

**Comment by lgritz** [comment]
> I have created PR to address this feature #4454 , but not able to add any reviewer.

Sigh. It's been a very busy day for the one volunteer who has been doing all the reviews.

**Comment by lgritz** [comment]
This was closed by #4454
