### ISSUE TITLE
[BUG] 16-bit psd files saved from photoshop not showing subimages

### ISSUE THREAD

**Issue by kpolonski** [AcademySoftwareFoundation/OpenImageIO#3900]
When using the python API to get subimage names or oiiotool to get info on all the subimages, a 16-bit photoshop file saved from windows photoshop shows no subimages. Saving the same photoshop file as an 8-bit file then shows all the layers. A little testing and it appears that 32-bit psd files exhibit the same behavior as 16-bit.

The attached psd files have 4 layers/subimages. Saved from photoshop 21.1.2 on windows.

_PSD files saved from Krita on linux as 16-bit images work fine, only psds from photoshop seem to show this behavior_

**To Reproduce**
Run oiiotool to see all subimage info for the 16-bit psd file vs. the 8-bit file
`oiiotool --info -v -a color_squares_small_16bit.psd`
The 8-bit file shows all the subimages while the 16-bit file does not.

**Expected behavior**
Show all relevant image info comparable to what the same file saved as 8-bit shows.

**Evidence**
`oiiotool --info -v -a color_squares_small_16bit.psd`
`oiiotool --info -v -a color_squares_small_8bit.psd`

Please find reproducing images attached.

**Platform information:**
 - OIIO branch/version: 2.4.11.0
 - OS: centos 7.6
 - C++ compiler: gcc 9.3.1
 - Any non-default build flags when you build OIIO: unknown, though I can find out if relevant

[color_squares_small.zip](https://github.com/OpenImageIO/oiio/files/11911258/color_squares_small.zip)

**Comment by EmilDohne** [comment]
Cross-posting the comment here. I explain in the discussion page why this isnt working and how it could be implemented:

https://github.com/AcademySoftwareFoundation/OpenImageIO/discussions/3910#discussioncomment-8913737

**Comment by lgritz** [comment]
@EmilDohne Is this issue fully solved by #4208? Can this one be closed?

**Comment by lgritz** [comment]
Fixed by #4208

**Comment by kpolonski** [comment]
Awesome news! Thanks so much @EmilDohne and @lgritz !

**Comment by lgritz** [comment]
I'm backporting this so it will be in (next month's) release patch.
