### ISSUE TITLE
[FEATURE REQUEST] idiff "directory mode"

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/OpenImageIO#4009]
On Unix/etc command line, the "diff" utility lets you say

    diff path/to/file1.txt anotherpath/toanother/file2.txt

but also if you 

    diff path/to/file1.txt pathto/dir

where `pathto/dir` is the name of a directory, this is shorthand for

    diff path/to/file1.txt pathto/dir/file1.txt

That is, you can just specify a directory as the second argument, and it knows that you mean to diff against a file of the same filename, in that other directory.

I would like our `idiff` utility to work the same way. You currently have to give both full paths, but many times I've wished you could give just a directory for the second name, and it would know what you meant and behave like `diff` users expect.

**Comment by davvid** [comment]
Hi Larry, I'd like to add this feature. Feel free to assign this to me. I actually already have this working locally but I might wait until the 12th before submitting the PR to help batch things up.

**Comment by lgritz** [comment]
I think you're the second person to say the same thing. But he seems to have deleted his comment here, so you're the winner.

**Comment by CheeksTheGeek** [comment]
Okayy!
