### ISSUE TITLE
[BUG] Large RGBA PNG write failure

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenImageIO#4044]
**Describe the bug**
I recently upgraded to 2.5.4.0 (from 2.3.10.0) and have been encountering Python crashes and `oiiotool` errors when writing large (>= ~5k square) RGBA PNG files. In both cases removing the alpha channel prior to writing resolves the issue. Smaller RGBA PNGs write without issue.

**To Reproduce**
Running this Python code causes a crash in my build:
```
buf = oiio.ImageBuf(oiio.ImageSpec(5000, 5000, 4, oiio.FLOAT))
oiio.ImageBufAlgo.fill(buf, (0.18, 0.18, 0.18, 1.0))
buf.write("/path/to/file.png")
```

This similar Python code will succeed with a much higher resolution image, but RGB only:
```
buf = oiio.ImageBuf(oiio.ImageSpec(16000, 16000, 3, oiio.FLOAT))
oiio.ImageBufAlgo.fill(buf, (0.18, 0.18, 0.18))
buf.write("/path/to/file.png")
```

Running this `oiiotool` command with an RGBA image >= ~5k square results in return code `3`:
```
oiiotool "/path/to/input.png" -o "/path/to/output.png"
```

If your input image is smaller, this fails too:
```
oiiotool "/path/to/input.png" --resample 5000x5000 -o "/path/to/output.png"
```

The same command will succeed if I drop the alpha channel prior to write:
```
oiiotool "/path/to/input.png" --resample 5000x5000 --ch R,G,B -o "/path/to/output.png"
```

**Evidence**
The `oiiotool` failure dumps this stack trace on exit:
```
 0# OpenImageIO_v2_5::Sysutil::hardware_concurrency in OpenImageIO_Util
 1# OpenImageIO_v2_5::Sysutil::stacktrace in OpenImageIO_Util
 2# OpenImageIO_v2_5::Sysutil::stacktrace in OpenImageIO_Util
 3# seh_filter_exe in ucrtbase
 4# 0x0000EDBE14EF1CB4 in oiiotool
 5# _C_specific_handler in VCRUNTIME140
 6# _chkstk in ntdll
 7# RtlRaiseException in ntdll
 8# KiUserExceptionDispatcher in ntdll
 9# memcpy in VCRUNTIME140
10# OpenImageIO_v2_5::copy_image in OpenImageIO
11# OpenImageIO_v2_5::convert_image in OpenImageIO
12# OpenImageIO_v2_5::png_output_imageio_create in OpenImageIO
13# OpenImageIO_v2_5::ImageOutput::write_image in OpenImageIO
14# OpenImageIO_v2_5::ImageBuf::write in OpenImageIO
15# 0x000013A651CECA7C in oiiotool
16# 0x00003B3C65694A08 in oiiotool
17# std::vector<OpenImageIO_v2_5::ParamValue,std::allocator<OpenImageIO_v2_5::ParamValue> >::_Destroy in OpenImageIO_Util
18# OpenImageIO_v2_5::ArgParse::parse_args in OpenImageIO_Util
19# OpenImageIO_v2_5::ArgParse::parse_args in OpenImageIO_Util
20# 0x0000519B8940721E in oiiotool
21# 0x0000DDF5BB65E2D7 in oiiotool
22# 0x0000E60E8A428DF3 in oiiotool
23# BaseThreadInitThunk in KERNEL32
24# RtlUserThreadStart in ntdll
```

**Platform information:**
 - OIIO branch/version: 2.5.4.0
 - OS: Windows 10
 - C++ compiler: MSVC 14.2
 - Any non-default build flags when you build OIIO:

**Comment by jessey-git** [comment]
I can confirm as well.  Seems like 101b8bb942987e204c59eed15e5d9ff6fe31081c may have impacted this.

We try to use a 64mb chunk buffer when writing out the scanlines, which equates to 5000x3392x4 worth of data, but the current `OIIO::convert_image` call wants to convert the entire 5000x5000 image.

**Comment by jessey-git** [comment]
@lgritz Are you able to take a look?

**Comment by lgritz** [comment]
Yeah, I have a very long airplane flight tomorrow, and hoping to catch up up a number of things I've neglected lately. Will try to take a look at this.

**Comment by lgritz** [comment]
Sorry for the ridiculous delay. I did find this bug while I was travelling, patch posted for review in #4074
