### ISSUE TITLE
[OpenEXR] Support for luminance chroma images

### ISSUE THREAD

**Issue by jreichel-nvidia** [AcademySoftwareFoundation/OpenImageIO#4051]
I'd like to request support for luminance chroma images, see https://openexr.com/en/latest/TechnicalIntroduction.html#luminance-chroma-images . An example texture can be found at https://github.com/AcademySoftwareFoundation/openexr-images/blob/main/LuminanceChroma/MtTamNorth.exr .

Right now the check for xSampling/ySampling at the end of OpenEXRInput::PartInfo::query_channels() fails with that example texture. Not sure whether generic sampling support is necessary. Maybe simply using the RGBA interface of OpenEXR in case of Y/RY/BY(/A) images is good enough? (That's what FreeImage is doing.)

**Comment by dazcjones** [comment]
This support would be great as luminance/chroma images can often be smaller in size for similar visual quality.

**Comment by lgritz** [comment]
Does anybody actually use subsampled Luminance/Chroma exr images, aside from testing conformance with the openexr-images examples? Do they exist in the wild?

They have a number of disadvantages -- in addition to being lossy, they only work for scanline images, and you have to read and buffer the whole image at once (to be able to interpolate, you can't process single scanlines at once). The RGBA interface only supports subsamples 1,1 or 2,2 (no other combinations) and doesn't support extra channels (including "layers").

Nuke doesn't read the RY/BY channels correctly, and doesn't support subsampled channels. Apple's Preview.app and Quickview also don't work with it. I've never seen an exr file with lum/chroma and/or subsampling used in real life, and in 15 years of OIIO history, I don't recall anybody complaining about lack of support.

It's definitely possible to add support for this, but before doing so, I want us to think carefully about whether the additional complexity is worth it, if it's not a file type anybody will ever encounter outside of trying to conformance test against the openexr-images samples.

For people who want to take advantage of chroma subsampling, I think the openexr team believes you should be using DWA compression. "I think anyone tempted to try chroma subsampling for efficiency might be better looking at DWA lossy compression of RGB, as that also does YCbCr conversion and is smarter than just blindly throwing away a bunch of chroma data in the hope that nobody will notice," is how Peter Hilman put it.

**Comment by lgritz** [comment]
Just for clarification, when you see in-the-wild images that are Luma/Chroma, are they also subsampled?
