### ISSUE TITLE
[BUG] Filenames containing ? are parsed as having REST parameters and fail to open

### ISSUE THREAD

**Issue by AdamMainsTL** [AcademySoftwareFoundation/OpenImageIO#4084]
**Describe the bug**
Trying to open a filename that contains a ? parses the file as if it contained REST parameters. This seems fine on Windows since ? is an invalid filename character, but on Mac it is a valid filename character.

**To Reproduce**
1. Name a file with a ? in it (e.g., ?.jpg)
2. Open the file
3. Get error: "ImageInput::create() called with malformed filename"

**Expected behavior**
File should open as it had any other normal name.

**Evidence**
The issue is that in `ImageInput::create` there is a call to `Strutil::get_rest_arguments`.
https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/de0d589d8cef5458ee726fb4db079de3cb47e222/src/libOpenImageIO/imageioplugin.cpp#L652-L656

`Strutil::get_rest_arguments` will return false if it finds a ? and no corresponding =.
https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/de0d589d8cef5458ee726fb4db079de3cb47e222/src/libutil/strutil.cpp#L322-L327

I can confirm this is the case because naming a file `?x=1.jpg` works fine, while `?.jpg` does not.

**Platform information:**
 - OIIO branch/version: 2.4.11.0, although code examples above taken from current master branch.
 - OS: Mac OS 14.2.1
 - C++ compiler: apple-clang
 - Any non-default build flags when you build OIIO:

**Comment by lgritz** [comment]
Do you actually have a file called "?.jpg" ?

**Comment by AdamMainsTL** [comment]
We have a lot of people who use our apps name photos with ? in them. I'm not sure why, but it's a more frequent complaint than I'd imagine.

**Comment by lgritz** [comment]
What do you think about this strategy: We could first check if the name passed is actually the name of an existing file, and if it is, use it directly and not do any of the REST processing. But if it's not the name of an existing file, only then scan for the REST related tokens?

**Comment by AdamMainsTL** [comment]
That sounds good to me. Part of the reason I didn't make a PR is because I was unsure how you'd want it handled. Is this something you'd prefer I take up or is it quick enough for you to throw it together?

**Comment by lgritz** [comment]
I'd definitely prefer you take it up!

Even when I have time, I think what we desperately need is to get everybody (including me) out of the habit of behaving in a way that makes so much bottlenecked on me. What others can do, others really should do, for the sake of de-risking the project.

**Comment by lgritz** [comment]
As we say: Mackerel!  🎣

**Comment by lgritz** [comment]
Closed by #4085
