### ISSUE TITLE
Last release doesn't appear in master

### ISSUE THREAD

**Issue by sambler** [AcademySoftwareFoundation/OpenImageIO#4154]
This is not really a bug report, so just post as question.

There is no entry in master CHANGES.md for 2.5.8.0.

The details can be seen in github when viewing by the tag or dev-2.5 branch, but they are not visible in master.

Does this mean other 2.5.8 changes have not been merged into master?

**Comment by lgritz** [comment]
No, it just means that I haven't yet gotten to adding that last set of changes in CHANGES.md itself to master. 

All code changes are made in master first and then cherry-picked into release branches. But the release notes of the patch releases are written in the release branch immediately prior to release, and then periodically added to master when I remember and get the chance.

**Comment by lgritz** [comment]
fixed
