### ISSUE TITLE
[BUG] 2.5.9.0 tries to link libxml2 but it looks like cmake doesnt check for the library

### ISSUE THREAD

**Issue by darix** [AcademySoftwareFoundation/OpenImageIO#4168]
**Describe the bug**

i tried to update the opensUSE package to 2.5.9.0 and it failed because that version needs libxml2 now.
shouldnt there be cmake find pkg for this then?

**Comment by lgritz** [comment]
Is this something that needs attention? I'm not aware that OIIO uses libxml2 directly.

**Comment by darix** [comment]
naw. solved already. it came in via dcmtk 

https://bugzilla.suse.com/show_bug.cgi?id=1220809
