### ISSUE TITLE
[FEATURE REQUEST] Metadata OpenEXR

### ISSUE THREAD

**Issue by TodicaIonut** [AcademySoftwareFoundation/OpenImageIO#4204]
**Is your feature request related to a problem? Please describe.**
OpenEXR files store metadata in attributes.

**Additional context**
add Metadata OpenEXR:
[Position and Orientation](https://openexr.com/en/latest/StandardAttributes.html#position-and-orientation)
[Camera ID](https://openexr.com/en/latest/StandardAttributes.html#camera-id)
[Camera State](https://openexr.com/en/latest/StandardAttributes.html#camera-state)
[Lens ID](https://openexr.com/en/latest/StandardAttributes.html#lens-id)
[Lens State](https://openexr.com/en/latest/StandardAttributes.html#lens-state)
[Editorial](https://openexr.com/en/latest/StandardAttributes.html#editorial)
[Encoded Image Color Characteristics](https://openexr.com/en/latest/StandardAttributes.html#encoded-image-color-characteristics)

**Comment by lgritz** [comment]
I'm not sure I understand the request. Can you please clarify? Do these not already get read and stored in the ImageSpec? Can you provide an example OpenEXR file with attributes that OIIO overlooks or doesn't allow you to retrieve?

**Comment by lgritz** [comment]
Closing, was an unclear request
