### ISSUE TITLE
[BUG] 16 and 32 bit PSD files fail to load correctly

### ISSUE THREAD

**Issue by jessey-git** [AcademySoftwareFoundation/OpenImageIO#4298]
**Describe the bug**

It seems as though the recent PSD changes are causing loading issues for 16 and 32bit files.

**OpenImageIO version and dependencies**

version: `2.5.11.0`
compiler: `MSVS 1929`
simd: `sse2`
dependencies: `Boost 1.82.0;fmt 9.1.0;JPEG 80;libjpeg-turbo NONE;OpenEXR 3.2.4;OpenJPEG 2.5;PNG 1.6.37;pugixml 1.10;pybind11 2.10.1;Python 3.11.7;Robinmap;TBB 2020.3;TIFF 4.6.0;WebP 1.3.2;ZLIB 1.2.13`

**To Reproduce**

1. Try loading https://github.com/AcademySoftwareFoundation/OpenImageIO-images/blob/master/psd_rgb_16.psd or https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/master/testsuite/psd/src/Layers_32bit_RGB.psd

**Evidence**

Result from https://github.com/AcademySoftwareFoundation/OpenImageIO-images/blob/master/psd_rgb_16.psd
![bad16](https://github.com/AcademySoftwareFoundation/OpenImageIO/assets/7989986/6203769a-8f9c-4279-aa3b-56dbf35ad605)

Result from https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/master/testsuite/psd/src/Layers_32bit_RGB.psd
![bad32](https://github.com/AcademySoftwareFoundation/OpenImageIO/assets/7989986/ae2fd2f4-87b9-429d-88e6-5b01d3499825)

**Comment by jessey-git** [comment]
The above images are from Blender - we updated to 2.5.11 recently and one user quickly discovered the issue.  I've also now been able to confirm with the OIIO `iv` tool using 2.5.12:

![bad32-iv](https://github.com/AcademySoftwareFoundation/OpenImageIO/assets/7989986/d37a7c59-0e36-49c2-aa59-6782d78c12a2)


CC @EmilDohne as FYI - Might you be able to take a look?

**Comment by lgritz** [comment]
For reference the patch that recently modified this was #4208.

**Comment by EmilDohne** [comment]
Hey @jessey-git that looks like some weird overflow issues. I will have a look :)

**Comment by jessey-git** [comment]
Reverting the changes to `PSDInput::read_channel_row` allows things to work again.

There's some suspect nesting in the switch statement there for sure, and differences from what was there before. The calls to swap_endian use `channel_info.width` instead of `m_spec.width` and these calls are now skipped for the `Compression_RLE` case.
If I "fix" the nesting and use `m_spec.width` I think that fixes things too but I'm not completely sure about this is general.
