### ISSUE TITLE
[BUILD] Can't build with latest OpenColorIO using vcpkg

### ISSUE THREAD

**Issue by davidarice** [AcademySoftwareFoundation/OpenImageIO#4327]
I'm having trouble building for Windows with the latest OpenColorIO using vcpkg. I can't only get OpenColorIO 2.2.1 instead of OpenColorIO 2.3.2 using `vcpkg install openimageio[tools,opencolorio]`

Output of `oiiotool --help`

`Input formats supported: bmp, cineon, dds, dpx, fits, hdr, iff, jpeg, null, openexr, pnm, psd, rla, sgi,
    softimage, targa, tiff, zfile
Output formats supported: bmp, dpx, fits, hdr, iff, jpeg, null, openexr, pnm, rla, sgi, targa, term, tiff, zfile
OpenColorIO 2.2.1
    Color config: ocio://default
    Run `oiiotool --colorconfiginfo` for a full color management inventory.
Filters available: box, triangle, gaussian, sharp-gaussian, catmull-rom, blackman-harris, sinc, lanczos3,
    radial-lanczos3, nuke-lanczos6, mitchell, bspline, disk, cubic, keys, simon, rifman
OIIO 2.6.3.0dev | unknown arch?
    Build compiler: MSVS 1938 | C++17/199711
    HW features enabled at build: sse2
    No CUDA support (disabled / unavailable at build time)
Dependencies: BZip2 1.0.8, DCMTK NONE, FFmpeg NONE, fmt 10.2.1, Freetype NONE, GIF NONE, Imath 3.1.10, JXL NONE,
    Libheif NONE, libjpeg-turbo 3.0.2, LibRaw NONE, **OpenColorIO 2.2.1**, OpenCV NONE, OpenEXR 3.2.3, OpenGL, OpenJPEG
    NONE, PNG NONE, Ptex NONE, Ptex NONE, pybind11 2.13.1, Python3 3.11.8, Qt5 NONE, Qt6 NONE, Robinmap 1.3.0, TBB
    NONE, TIFF 4.6.0, WebP NONE, ZLIB 1.3.1`

**Comment by lgritz** [comment]
I'm not a vcpkg expert, but I'm pretty sure it just gives you whatever OCIO that vcpkg specifies. I believe this result indicates that somebody who takes care of the vcpkg recipe for OCIO needs to adjust which version it builds.

**Comment by davidarice** [comment]
Gotcha. Did another search and according to this: [https://stackoverflow.com/questions/69252632/vcpkg-how-do-i-submit-a-request-for-a-package-update-or-see-if-the-package-is](url) It's up to the package maintainers to submit a pull request to vcpkg. [https://github.com/microsoft/vcpkg/pulls](url)

Hoping this can be done by someone here?

**Comment by lgritz** [comment]
I think there is some ambiguous language used in that explanation. Who are the "package maintainers" they are referring to? 

For any of the major distributions or packaging systems (whether it be vcpkg, homebrew, Fedora, Conan, etc.), there are:

- the people who write the packaging system?(like vcpkg, homebrew, fedora, conan, etc.)
- the people who write the package (OpenImageIO, OpenColorIO, etc.)
- the people who maintain the package system's recipe for the package

It has always been the third group who has done this. I'm pretty sure that nobody here (in the second group) has ever been involved in exactly how the vcpkg recipes (or any of the others!) are made. The fact that they're using reasonably modern versions certainly means that SOMEBODY is doing it. The trick is to find those people. Maybe see who has been submitting the PRs against vcpkg historically as relates to these packages?

I'm looking at what I just wrote with some horror. I don't like that we're pointing fingers in some other direction. But the fact is that it hasn't been the maintainers of OCIO or OIIO thus far, and I'm not sure they have any expertise in how to correctly write the vcpkg recipes.

**Comment by davidarice** [comment]
I gotta read up on vcpkg and see if there's a way to do the building manually. I'm very familiar with it all.

**Comment by lgritz** [comment]
Any update here? Should we hold this issue open, or close it?

**Comment by davidarice** [comment]
I think it's fine to close. It's a vcpkg issue I guess at this point.

**Comment by Glatzel** [comment]
Hello @davidarice 
I also meet the problem. Have you found the solution to install with ocio 2.3?

**Comment by davidarice** [comment]
2.4.2 is now available. https://vcpkg.io/en/package/opencolorio
