### ISSUE TITLE
[BUG] inconsistent results of ImageBuf colorconvert in built without OCIO and with OCIO.

### ISSUE THREAD

**Issue by ssh4net** [AcademySoftwareFoundation/OpenImageIO#4331]
**Describe the bug**

Inconsistent results of ImageBuf colorconvert() when OpenImageIO built without OpenColorIO and with OpenColorIO.
Quite common case when oiiotools usually building in vcpkg in a minimal configuration `openimageio[core,oiiotools].`
Or with OCIO support `openimageio[core,oiiotools,opencolorio]`.

As result any example from OIIO documentation give a different resul when OCIO enabled or disabled.
That happen because default color space for OCIO is ACES-AP1 (ACEScg) and no "linear" color space defined.

Libraw plugin in same time use "standard" naming for sRGB, linear, aces, etc.
And "linear" color space are alias for sRGB LInear.

Issue i feel is more complicated due to OCIO forcing to use it own conventions and ignoring the facts that a lot of work spaces still understand sRGB as default color space and Linear is a "sRGB Linear". So any fix will be just a patch to fix OCIO issue when actual OIIO code is correct.

**To Reproduce**

`oiiotool photo.jpg --colorconvert sRGB linear -o output.exr`

depend on OCIO result will be a sRGB Linear or ACEScg exr file.
Same in other direction. 

`oiiotool photo.jpg --colorconvert linear sRGB -o output.exr`
with OCIO input will be treat as ACEScg and sRGB result will be incorrect.

**Comment by lgritz** [comment]
Closing because in the master branch that will become 3.0, OCIO is now a required dependency, so we should no longer have to worry about behavior differences that might be present when OIIO is built without OCIO support -- that just won't happen any more.
