### ISSUE TITLE
Consider adopting signed release tags 

### ISSUE THREAD

**Issue by cary-ilm** [AcademySoftwareFoundation/OpenImageIO#4403]
The OpenSSF Best Practices Badge suggests [signing release tags](https://www.bestpractices.dev/en/criteria). The process is simple, described [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-tags): simply create the release from a tag created with `-s`:

`$ git tag -s v1.2.3`

The project maintainer who creates the release tags needs a GPG key. Instructions for creating a key are described [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key).

**Comment by lgritz** [comment]
@cary-ilm, a few questions about the logistics:

- Do you just make a personal gpg key for signing release tags?
- Does that mean you're the only one who can do the signing?
- If a project wants multiple people to be able to tag releases, how should that be achieved?
- Does it matter if some tags are signed by one person/key, and other release tags use a different key?
- How does somebody on the other end use this? OK, so it's a tagged release. Could be that anybody signed it and pushed the tag, no? Is there a way to tell GitHub to only draft a release if it's been signed by a *particular* person or people? How do you document for users how to determine if a signed tag is legit?

**Comment by cary-ilm** [comment]
Apologies, I missed this when it came in.

As I understand it, the signed tag can be created/signed by anyone with push access on the repo, i.e. a maintainer, so presumably each maintainer could sign with their own key. The signed tag has info in it that says who signed it.

The only way for a signed tag to make it into the repo is for a maintainer to push it. So presumably it's up to the maintainers to ensure that they push only tags signed by people authorized to sign.

**Comment by lgritz** [comment]
But the only people who can push a tag or draft a release in GH are maintainers. So what does it really prove? I guess... it can catch a case where somebody compromises the GH account of a maintainer (so can push the tag) but hasn't also gotten their hands on the maintainer's private key? But only if the downstream recipient diligently checks that the tag they're using for a build is a signed tag. I guess every little bit helps, but that strikes me as a very narrow set of circumstances that it protects against. Or am I missing something?
