### ISSUE TITLE
[BUG] ImageBufAlgo::demosaic work only with float ImageBuf

### ISSUE THREAD

**Issue by ssh4net** [AcademySoftwareFoundation/OpenImageIO#4416]
`ImageBuf demosaiced = ImageBufAlgo::demosaic(input, { {"algorithm", "linear"}, {"pattern", "bayer"}, {"layout", "RGGB"} });`

output zero for uint8/uint16 ImageBuf

this code will output black image.
```
ImageBuf input(file.string(), 0, 0, nullptr, &spec, nullptr);
ImageBuf demosaiced = ImageBufAlgo::demosaic(input, { {"algorithm", "linear"}, {"pattern", "bayer"}, {"layout", "RGGB"} });
newfile = "demosaic.exr";
demosaiced.write(newfile);
```

This code that convert uint to float on load will output correctly demosaiced image
```
ImageBuf input(file.string());
input.read(0, 0, true, TypeDesc::FLOAT, nullptr, nullptr);
ImageBuf demosaiced = ImageBufAlgo::demosaic(input, { {"algorithm", "linear"}, {"pattern", "bayer"}, {"layout", "RGGB"} });
newfile = "demosaic.exr";
demosaiced.write(newfile);
```

tested on latest master.

(Looks like tests are use only floats images?)

**Comment by antond-weta** [comment]
I've fixed the bug and got uint8/uint16 images covered in unit tests. See #4419
Thanks for reporting this.

**Comment by ssh4net** [comment]
Thanx! Now everything works.
