### ISSUE TITLE
[FEATURE REQUEST] HDR Gain map support

### ISSUE THREAD

**Issue by filmkorn** [AcademySoftwareFoundation/OpenImageIO#4424]
**Is your feature request related to a problem? Please describe.**
- Providing compatible HDR content for an increasing number of HDR capable devices.

**Describe the solution you'd like**
Proposing to add support for gain maps in OIIO to read/write backwards compatible jpg images with gain maps.
- Add reader and writer plugins for libultrahdr. Existing support in Chrome to view these seems beneficial.

**Describe alternatives you've considered**
- ImageMagick appears to have support for UltraHDR.

**Additional context**
- https://www.iso.org/standard/86775.html
- https://github.com/google/libultrahdr/
- https://github.com/libjpeg-turbo/libjpeg-turbo/issues/746

**Comment by lgritz** [comment]
This is apparently an extension to JPEG that stashes an extra part to the file that includes the HDR information (readers that don't know about this just see the part that's the ordinary SDR JPEG image.

This would be great for somebody to tackle as a modification to our JPEG reader.

🎣 Mackerel!

**Comment by mugulmd** [comment]
I can take a stab at it if that's alright with everyone!

**Comment by lgritz** [comment]
Yes, please, @mugulmd !

**Comment by lgritz** [comment]
Implemented by #4484
