### ISSUE TITLE
Problems with font enumeration

### ISSUE THREAD

**Issue by peterhorvath111** [AcademySoftwareFoundation/OpenImageIO#4504]
While using OIIO in Arnold to render text over our rendered images, we discovered a few issues regarding the current (2.5.16) font enumeration code.

- HOME environment variable is not defined on Windows. Windows instead uses `%HOMEDRIVE%%HOMEPATH%`.
- User specific system font directory is not searched on Windows. That is `%LOCALAPPDATA%/Microsoft/Windows/Fonts`.
- `$HOME/.fonts` and `$HOME/.local/share/fonts` are valid system folders on some linux distros, that are currently not searched.
- Duplicated entries in the search folders. For instance on Windows, both, `%SystemRoot%` and `C:/Windows` is added, but they are the same.
- The current implementation looks for fonts in subfolders one level deep. That allows folders that are not standard system folders. For instance on Windows subfolders are not supported natively. Also this might be expensive, for instance the current code reads all folders from `C:\Windows` and the system root on other platforms, unnecessarily.
- Fonts are now loaded from folders that are not standard system font folders. For instance `%HOME%/usr/share/fonts` on Windows, that is not a standard font folder.
- The code is hard to read, hard to tell which folders are searched/valid on each platform.

We've got fixes for some of the issues above that we can port back. 

I'd also suggest to simplify the code and instead of using prefixes and suffixes, adding only known system font folders (global and user) per each platform. And allow defining custom font folders via the `OPENIMAGEIO_FONTS` environment variable. What do you think?

**Comment by lgritz** [comment]
Sounds good to me. I welcome a principled overhaul.

**Comment by zachlewis** [comment]
Would you mind checking for fonts in `$OpenImageIO_ROOT/share/fonts` too?

**Comment by peterhorvath111** [comment]
Created PR #4508 with the suggested changes.
