### ISSUE TITLE
CPack tweakage

### ISSUE THREAD

**Issue by dan-eicher** [AcademySoftwareFoundation/OpenImageIO#72]
Couple changes to make CPack work on Fedora 14 (and I'd imagine Debian/Ubuntu too)

CPACK_PACKAGE_CONTACT (needed for .deb) also probably needs a valid email.

Patch:
http://www.pasteall.org/21173/diff

**Comment by lgritz** [comment]
This has gone without comment for a long time and the link showing the patch no longer works, so I'm going to close.

I'm just going to cop to having dropped this one on the floor. If it's something that anyone cares about, please refile or better, submit a PR that makes the fix that this would involve.
